module serpent:
    snakefile: "/home/jb/development/serpent/workflow/Snakefile"

BFILES={k: f"data/act/{k}/CleanedGenotypes/{v}" for k, v in config["bfiles"].items()}
MARGIN_MAP = {
    "var": "by.variant",
    "samp": "by.sample"
}
MARGIN = list(MARGIN_MAP.keys())
wildcard_constraints:
    cohort="|".join(list(BFILES.keys())),
    margin="|".join(MARGIN),



rule check_sex:
    container: config["images"]["plink"]
    input:
        bed=lambda wildcards: f"{BFILES[wildcards.cohort]}.bed",
        bim=lambda wildcards: f"{BFILES[wildcards.cohort]}.bim",
        fam=lambda wildcards: f"{BFILES[wildcards.cohort]}.fam",
    output:
        sexcheck=temp("temp/{cohort}/sexcheck.txt"),
    log: "logs/check-sex/{cohort}.log"
    shell:
        """
        outdir=act-plink-check-sex-{wildcards.cohort}
        mkdir -p $outdir
        pfx=$outdir/plink
        plink --bed {input.bed} \
            --bim {input.bim} \
            --fam {input.fam} \
            --check-sex \
            --out $pfx
        mv $pfx.sexcheck {output.sexcheck}
        mv $pfx.log {log}
        rm -rf $outdir
        """

use rule parse_sexcheck from serpent as serpent_parse_sexcheck with:
    container: config["images"]["shiny_verse"]
    input:
        sexcheck=rules.check_sex.output.sexcheck
    output:
        sexcheck="temp/{cohort}/sexcheck.rds",
        ok="temp/{cohort}/pass_sexcheck.rds",
        fail="temp/{cohort}/fail_sexcheck.rds",
        summary="temp/{cohort}/sexcheck_summary.txt",
    log: "logs/{cohort}/parse_sexcheck.log"
    container: config["images"]["shiny_verse"]

M_VCF_OUT_PFX = f"{config["outdir"]["act"]["process_vcf"]}/results/vcf/chr{{chromosome}}_filtered.vcf.gz"
rule get_ids:
    container: config["images"]["bcftools"]
    input:
        vcf=M_VCF_OUT_PFX,
        tbi=f"{M_VCF_OUT_PFX}.tbi"
    output: temp("results/typed_ids/chr{chromosome}_typed_ids.txt"),
    log: "logs/get_ids/{chromosome}.log"
    shell:
        """
        bcftools query -l {input} > {output} 2> {log}
        """

rule combine_ids:
    input: expand(rules.get_ids.output, cohort=list(BFILES.keys()), chromosome=config["CHROMOSOMES"])
    output: "results/typed_ids.txt"
    log: "logs/combine_ids.log"
    shell:
        """
        cat {input} > {output} 2> {log}
        """

rule get_bps_samples:
    container: config["images"]["shiny_verse"]
    input:
        bps="{config['data']['act']}/act_bps.txt",
        xwalk="{config['data']['act']}/ACT_ID_xwalk.csv",
        typed_ids=rules.combine_ids.output,
    output:
        txt="results/np_ids.txt",
        rds="results/np_ids.rds",
        ids_matched="results/ids_matched.csv",
    log: "logs/get_bps_samples.log"
    script: "scripts/extract_ids.R"

rule get_cohorts:
    container: config["images"]["shiny_verse"]
    input:
        fam=lambda wildcards: f"{BFILES[wildcards.cohort]}.fam",
        np_ids=rules.get_bps_samples.output.rds,
        var_ids="results/{cohort}/var_ids.rds",
    output:
        ids="results/{cohort}_ids.rds",
        hwe_ids="results/{cohort}_hwe_ids.rds",
    log: "logs/{cohort}/get_cohorts.log"
    script: "scripts/get_cohorts.R"

GDS=f"{config["outdir"]["act"]["convert_gt_gds"]}/act_genotyped.gds"
rule get_var_ids:
    container: config["images"]["genesis"]
    input:
        bim=lambda wildcards: f"{BFILES[wildcards.cohort]}.bim",
        gds=GDS,
    output:
        var_ids = "results/{cohort}/var_ids.rds"
    log: "logs/{cohort}/get_var_ids.log"
    threads: 30
    script:
        "scripts/get_var_ids.R"

use rule seqMissing from serpent as serpent_seqMissing with:
    container: config["images"]["genesis"]
    input:
        gds_fn=GDS,
        sample_id="results/{cohort}_ids.rds",
        variant_id="results/{cohort}/var_ids.rds",
    output: 
        "temp/{cohort}_ms_{by_var}.rds"
    log: "logs/{cohort}/ms_{by_var}.log"
    params:
        seqMissing_args=lambda wildcards: {
            "per.variant": BY_VAR_MAP[wildcards.by_var],
            "verbose": True,
        }
    threads: 30


use rule hwe from serpent as serpent_hwe with:
    container: config["images"]["genesis"]
    input:
        gds_fn=GDS,
        sample_id="results/{cohort}_hwe_ids.rds",
    output: "results/{cohort}_hwe.rds"
    log: "logs/{cohort}/hwe.log"
    params:
        seed=51,
        parallel=True,
    threads: workflow.cores

use rule heterozygosity from serpent as serpent_heterozygosity with:
    container: config["images"]["genesis"]
    input:
        gds_fn=GDS,
        sample_id="results/{cohort}_ids.rds",
        variant_id="results/{cohort}/var_ids.rds",
    output: "results/{cohort}_htz_{margin}.rds"
    log: "logs/{cohort}/heterozygosity_{margin}.log"
    params:
        heterozygosity_args=lambda wildcards: {
            "margin": MARGIN_MAP[wildcards.margin],
        }
    threads: 30

use rule combine_varmet from serpent as serpent_combine_varmet with:
    container: config["images"]["genesis"]
    input:
        ms="temp/{cohort}_ms_var.rds",
        hwe="results/{cohort}_hwe.rds",
        htz="results/{cohort}_htz_var.rds",
    output:
        var_qc="results/{cohort}/var_qc.rds"
    log: "logs/{cohort}/combine_varmet.log"

rule sample_qc:
    container: config["images"]["shiny_verse"]
    input:
        samp_ms=expand("temp/{cohort}_ms_samp.rds", cohort=list(BFILES.keys())),
        sexcheck=expand("temp/{cohort}/sexcheck.rds", cohort=list(BFILES.keys())),
        samp_htz=expand("results/{cohort}_htz_samp.rds", cohort=list(BFILES.keys())),
        np_ids="results/np_ids.rds",
    output:
        keep="results/samples_pass_qc.rds",
        sampmet="results/sample_metrics.rds",
    params:
        cohorts=list(BFILES.keys()),
        samp_ms = 0.1,
        htz_sd = 3,
    log: "logs/sample_qc.log"
    script: "scripts/sample_qc.R"

rule variant_qc:
    container: config["images"]["shiny_verse"]
    input:
        var_qc="results/{cohort}/var_qc.rds",
    output:
        varmet="results/{cohort}/variant_metrics.rds",
        keep="results/{cohort}/variants_pass_qc.rds",
    log: "logs/{cohort}/variant_qc.log"
    params:
        var_ms = 0.01,
        hwe_p = 1e-4,
    script: "scripts/variant_qc.R"

rule parse_varmet:
    container: config["images"]["shiny_verse"]
    input:
        varmet=expand("results/{cohort}/variant_metrics.rds", cohort=list(BFILES.keys())),
        sampmet="results/sample_metrics.rds",
    output:
        varmet="results/variant_metrics_combined.rds",
        keep="results/variants_pass_qc.rds",
    log: "logs/parse_varmet.log"
    params:
        cohort=list(BFILES.keys()),
    script: "scripts/parse_varmet.R"

rule qc_report:
    container: config["images"]["shiny_verse"]
    input:
        sampmet="results/sample_metrics.rds",
        samp_keep="results/samples_pass_qc.rds",
        varmet="results/variant_metrics_combined.rds",
        var_keep="results/variants_pass_qc.rds",
    output:
        html="notebooks/act_qc_report.html",
    params:
        cohorts=list(BFILES.keys()),
    script: "scripts/qc_report.Rmd"
