module serpent:
    snakefile: "/home/jb/development/serpent/workflow/Snakefile"

OUTDIR = config["act"]["outdir"]["sample_variant_qc"]

rule all:
    input: f"{OUTDIR}/notebooks/act_qc_report.html",

BFILES={k: f"/container/act/{k}/CleanedGenotypes/{v}" for k, v in config["bfiles"].items()}
MARGIN_MAP = {
    "var": "by.variant",
    "samp": "by.sample"
}
MARGIN = list(MARGIN_MAP.keys())
BY_VAR_MAP = {
    "var": True,
    "samp": False
}
BY_VAR = list(BY_VAR_MAP.keys())
wildcard_constraints:
    cohort="|".join(list(BFILES.keys())),
    margin="|".join(MARGIN),
    by_var="|".join(BY_VAR),

rule check_sex:
    container: config["images"]["plink"]
    input:
        bed=lambda wildcards: f"{BFILES[wildcards.cohort]}.bed",
        bim=lambda wildcards: f"{BFILES[wildcards.cohort]}.bim",
        fam=lambda wildcards: f"{BFILES[wildcards.cohort]}.fam",
    output:
        sexcheck=temp(f"{OUTDIR}/temp/{{cohort}}/sexcheck.txt"),
    log: f"{OUTDIR}/logs/check-sex/{{cohort}}.log"
    shell:
        """
        outdir=act-plink-check-sex-{wildcards.cohort}
        mkdir -p $outdir
        pfx=$outdir/plink
        plink --bed {input.bed} \
            --bim {input.bim} \
            --fam {input.fam} \
            --check-sex \
            --out $pfx
        mv $pfx.sexcheck {output.sexcheck}
        mv $pfx.log {log}
        rm -rf $outdir
        """

use rule parse_sexcheck from serpent as serpent_parse_sexcheck with:
    container: config["images"]["shiny_verse"]
    input:
        sexcheck=rules.check_sex.output.sexcheck
    output:
        sexcheck=f"{OUTDIR}/temp/{{cohort}}/sexcheck.rds",
        ok=f"{OUTDIR}/temp/{{cohort}}/pass_sexcheck.rds",
        fail=f"{OUTDIR}/temp/{{cohort}}/fail_sexcheck.rds",
        summary=f"{OUTDIR}/temp/{{cohort}}/sexcheck_summary.txt",
    log: f"{OUTDIR}/logs/{{cohort}}/parse_sexcheck.log"
    container: config["images"]["shiny_verse"]

M_VCF_OUT_PFX = f"{config["act"]["outdir"]["process_vcf"]}/results/vcf/chr{{chromosome}}_filtered.vcf.gz"
rule get_ids:
    container: config["images"]["bcftools"]
    input:
        vcf=M_VCF_OUT_PFX,
        tbi=f"{M_VCF_OUT_PFX}.tbi"
    output: temp(f"{OUTDIR}/results/typed_ids/chr{{chromosome}}_typed_ids.txt"),
    log: f"{OUTDIR}/logs/get_ids/{{chromosome}}.log"
    shell:
        """
        bcftools query -l {input} > {output} 2> {log}
        """

rule combine_ids:
    input: expand(rules.get_ids.output, chromosome=config["CHROMOSOMES"])
    output: f"{OUTDIR}/results/typed_ids.txt"
    log: f"{OUTDIR}/logs/combine_ids.log"
    shell:
        """
        cat {input} > {output} 2> {log}
        """

rule get_bps_samples:
    container: config["images"]["shiny_verse"]
    input:
        bps="/container/act/act_bps.txt",
        xwalk="/container/act/ACT_ID_xwalk.csv",
        typed_ids=rules.combine_ids.output,
    output:
        txt=f"{OUTDIR}/results/np_ids.txt",
        rds=f"{OUTDIR}/results/np_ids.rds",
        ids_matched=f"{OUTDIR}/results/ids_matched.csv",
    log: f"{OUTDIR}/logs/get_bps_samples.log"
    script: "scripts/extract_ids.R"

rule get_cohorts:
    container: config["images"]["shiny_verse"]
    input:
        fam=lambda wildcards: f"{BFILES[wildcards.cohort]}.fam",
        np_ids=rules.get_bps_samples.output.rds,
        var_ids=f"{OUTDIR}/results/{{cohort}}/var_ids.rds",
    output:
        ids=f"{OUTDIR}/results/{{cohort}}_ids.rds",
        hwe_ids=f"{OUTDIR}/results/{{cohort}}_hwe_ids.rds",
    log: f"{OUTDIR}/logs/{{cohort}}/get_cohorts.log"
    script: "scripts/get_cohorts.R"

GDS=f"{config['act']['outdir']['convert_gt_gds']}/results/act_genotyped.gds"
rule get_var_ids:
    container: config["images"]["genesis"]
    input:
        bim=lambda wildcards: f"{BFILES[wildcards.cohort]}.bim",
        gds=GDS,
    output:
        var_ids = f"{OUTDIR}/results/{{cohort}}/var_ids.rds"
    log: f"{OUTDIR}/logs/{{cohort}}/get_var_ids.log"
    threads: 30
    script:
        "scripts/get_var_ids.R"

use rule seqMissing from serpent as serpent_seqMissing with:
    container: config["images"]["genesis"]
    input:
        gds_fn=GDS,
        sample_id=f"{OUTDIR}/results/{{cohort}}_ids.rds",
        variant_id=f"{OUTDIR}/results/{{cohort}}/var_ids.rds",
    output: 
        f"{OUTDIR}/temp/{{cohort}}_ms_{{by_var}}.rds"
    log: f"{OUTDIR}/logs/{{cohort}}/ms_{{by_var}}.log"
    params:
        seqMissing_args=lambda wildcards: {
            "per.variant": BY_VAR_MAP[wildcards.by_var],
            "verbose": True,
        }
    threads: 30


use rule hwe from serpent as serpent_hwe with:
    container: config["images"]["genesis"]
    input:
        gds_fn=GDS,
        sample_id=f"{OUTDIR}/results/{{cohort}}_hwe_ids.rds",
    output: f"{OUTDIR}/results/{{cohort}}_hwe.rds"
    log: f"{OUTDIR}/logs/{{cohort}}/hwe.log"
    params:
        seed=51,
        parallel=True,
    threads: workflow.cores

use rule heterozygosity from serpent as serpent_heterozygosity with:
    container: config["images"]["genesis"]
    input:
        gds_fn=GDS,
        sample_id=f"{OUTDIR}/results/{{cohort}}_ids.rds",
        variant_id=f"{OUTDIR}/results/{{cohort}}/var_ids.rds",
    output: f"{OUTDIR}/results/{{cohort}}_htz_{{margin}}.rds"
    log: f"{OUTDIR}/logs/{{cohort}}/heterozygosity_{{margin}}.log"
    params:
        heterozygosity_args=lambda wildcards: {
            "margin": MARGIN_MAP[wildcards.margin],
        }
    threads: 30

use rule combine_varmet from serpent as serpent_combine_varmet with:
    container: config["images"]["genesis"]
    input:
        ms=f"{OUTDIR}/temp/{{cohort}}_ms_var.rds",
        hwe=f"{OUTDIR}/results/{{cohort}}_hwe.rds",
        htz=f"{OUTDIR}/results/{{cohort}}_htz_var.rds",
    output:
        var_qc=f"{OUTDIR}/results/{{cohort}}/var_qc.rds"
    log: f"{OUTDIR}/logs/{{cohort}}/combine_varmet.log"

rule sample_qc:
    container: config["images"]["shiny_verse"]
    input:
        samp_ms=expand(f"{OUTDIR}/temp/{{cohort}}_ms_samp.rds", cohort=list(BFILES.keys())),
        sexcheck=expand(f"{OUTDIR}/temp/{{cohort}}/sexcheck.rds", cohort=list(BFILES.keys())),
        samp_htz=expand(f"{OUTDIR}/results/{{cohort}}_htz_samp.rds", cohort=list(BFILES.keys())),
        np_ids=f"{OUTDIR}/results/np_ids.rds",
    output:
        keep=f"{OUTDIR}/results/samples_pass_qc.rds",
        sampmet=f"{OUTDIR}/results/sample_metrics.rds",
    params:
        cohorts=list(BFILES.keys()),
        samp_ms = 0.1,
        htz_sd = 3,
    log: f"{OUTDIR}/logs/sample_qc.log"
    script: "scripts/sample_qc.R"

rule variant_qc:
    container: config["images"]["shiny_verse"]
    input:
        var_qc=f"{OUTDIR}/results/{{cohort}}/var_qc.rds",
    output:
        varmet=f"{OUTDIR}/results/{{cohort}}/variant_metrics.rds",
        keep=f"{OUTDIR}/results/{{cohort}}/variants_pass_qc.rds",
    log: f"{OUTDIR}/logs/{{cohort}}/variant_qc.log"
    params:
        var_ms = 0.01,
        hwe_p = 1e-4,
    script: "scripts/variant_qc.R"

rule parse_varmet:
    container: config["images"]["shiny_verse"]
    input:
        varmet=expand(f"{OUTDIR}/results/{{cohort}}/variant_metrics.rds", cohort=list(BFILES.keys())),
        sampmet=f"{OUTDIR}/results/sample_metrics.rds",
    output:
        varmet=f"{OUTDIR}/results/variant_metrics_combined.rds",
        keep=f"{OUTDIR}/results/variants_pass_qc.rds",
    log: f"{OUTDIR}/logs/parse_varmet.log"
    params:
        cohort=list(BFILES.keys()),
    script: "scripts/parse_varmet.R"

rule qc_report:
    container: config["images"]["shiny_verse"]
    input:
        sampmet=f"{OUTDIR}/results/sample_metrics.rds",
        samp_keep=f"{OUTDIR}/results/samples_pass_qc.rds",
        varmet=f"{OUTDIR}/results/variant_metrics_combined.rds",
        var_keep=f"{OUTDIR}/results/variants_pass_qc.rds",
    output:
        html=f"{OUTDIR}/notebooks/act_qc_report.html",
    params:
        cohorts=list(BFILES.keys()),
    script: "scripts/qc_report.Rmd"
